"use client";
import { buildRepairIssues } from "../../lib/map-repair";
import { validateWorld } from "../../lib/studio/validation";
import type { Job, Stroke, StudioRecipe, World } from "../../lib/studio/model";
import { ClimateControls, Field, Slider } from "./recipe-panel";
import { useState } from "react";

export function DevelopPanel({ world, recipe, onRecipe, selection, busy, run, operation, onOperation, strength, onStrength, brush, onBrush, paint, onPaint, onSketch, onMetadata }: {
  world: World; recipe: StudioRecipe; onRecipe: (r: StudioRecipe) => void; selection: number[]; busy: boolean; run: (job: Job, label: string) => void;
  operation: Stroke["kind"]; onOperation: (s: Stroke["kind"]) => void; strength: number; onStrength: (n: number) => void; brush: number; onBrush: (n: number) => void;
  paint: { terrain: number; elevation: number; feature: number; resource: number }; onPaint: (p: { terrain: number; elevation: number; feature: number; resource: number }) => void; onSketch: () => void;
  onMetadata: (change: Partial<{ name: string; description: string }>) => void;
}) {
  return <fieldset disabled={busy} className="studio-development">
    <div className="studio-panel-heading"><h2>Develop this world</h2><p>Keep its recognizable places and explore what they could become.</p></div>
    <button className="studio-full" onClick={() => run({ kind: "DEVELOP", world, selection }, selection.length ? "Develop the selected place" : "Consider local developments")}>Suggest developments{selection.length ? " here" : ""}</button>
    <div className="studio-proposals" aria-live="polite">{world.development.proposals.map(proposal => <section className="studio-proposal" key={proposal.id}><h3>{proposal.title}</h3><p>{proposal.reason}</p><details><summary>Trade-off & footprint</summary><p>{proposal.tradeoff}</p><p>{proposal.changed.toLocaleString()} tiles would change, including dependent geography.</p>{proposal.effects?.filter(effect => effect.before !== effect.after).map(effect => <p key={effect.label}>{effect.label}: {effect.before} → {effect.after}</p>)}</details><button onClick={() => run({ kind: "DEVELOP", world, proposalId: proposal.id }, proposal.title)}>Preview development</button></section>)}</div>
    <details open={!!selection.length}><summary>Shape a place <span>{selection.length ? `${selection.length} tiles` : "Select or sketch"}</span></summary>
      <Field label="Operation"><select value={operation} onChange={e => onOperation(e.target.value as Stroke["kind"])}><option value="RIDGE">Raise a range</option><option value="BASIN">Deepen a basin</option><option value="LAND">Raise land</option><option value="PASS">Open a saddle</option><option value="WET">Develop a wetter landscape</option><option value="DRY">Develop a drier landscape</option><option value="WARM">Warm a region</option><option value="COOL">Cool a region</option><option value="PAINT">Exact tile edit</option></select></Field>
      <Slider label="Brush width" min={1} max={6} value={brush} onChange={onBrush} /><Slider label="Strength" min={10} value={strength} onChange={onStrength} />
      {operation === "PAINT" && <><Field label="Terrain"><select value={paint.terrain} onChange={e => onPaint({ ...paint, terrain: Number(e.target.value) })}>{world.map.terrains.map((name, i) => <option key={i} value={i}>{name.replace("TERRAIN_", "")}</option>)}</select></Field><Field label="Relief"><select value={paint.elevation} onChange={e => onPaint({ ...paint, elevation: Number(e.target.value) })}><option value={0}>Flat</option><option value={1}>Hills</option><option value={2}>Mountain</option></select></Field><Field label="Feature"><select value={paint.feature} onChange={e => onPaint({ ...paint, feature: Number(e.target.value) })}><option value={255}>None</option>{world.map.features.map((name, i) => <option key={i} value={i}>{name.replace("FEATURE_", "")}</option>)}</select></Field><Field label="Resource"><select value={paint.resource} onChange={e => onPaint({ ...paint, resource: Number(e.target.value) })}><option value={255}>None</option>{world.map.resources.map((name, i) => <option key={i} value={i}>{name.replace("RESOURCE_", "")}</option>)}</select></Field></>}
      <button className="studio-full studio-primary" disabled={!selection.length} onClick={onSketch}>Preview selected change</button>
    </details>
    <details><summary>Climate & drainage</summary><ClimateControls recipe={recipe} onChange={onRecipe} /></details>
    <button className="studio-full" onClick={() => run({ kind: "REFINE", world, recipe }, "Developed climate and drainage")}>Preview world changes</button>
    <details><summary>Name & description</summary><Field label="Map name"><input key={world.map.name} defaultValue={world.map.name} maxLength={200} onBlur={e => { const name = e.target.value.trim(); if (!name) e.target.value = world.map.name; else if (name !== world.map.name) onMetadata({ name }); }} /></Field><textarea className="studio-description" aria-label="Map description" key={world.map.description} defaultValue={world.map.description} maxLength={2000} onBlur={e => { if (e.target.value !== world.map.description) onMetadata({ description: e.target.value }); }} /></details>
    <details><summary>Retained foundation</summary><p className="studio-caption">{world.substrate.confidence === "NATIVE" ? "Native geographic plans and continuous fields are retained." : world.substrate.confidence === "RETAINED" ? "This foundation preserves the geography and fields of an earlier edited map." : "This foundation preserves observed terrain. Its physical fields are inferred."}</p><p className="studio-caption">{world.features.length} recognizable places · {world.development.operations.length} recorded map operations.</p>{world.development.operations.slice(0, 12).map(operation => <p className="studio-caption" key={operation.id}>{operation.label}{operation.inferred ? " · inferred" : ""}</p>)}</details>
  </fieldset>;
}
export function ReviewPanel({ world, busy, run }: { world: World; busy: boolean; run: (job: Job, label: string) => void }) {
  const [chosen, setChosen] = useState<string[]>([]), [balance, setBalance] = useState<StudioRecipe["balance"]>("STRATEGIC");
  const assessment = world.assessment, issues = buildRepairIssues(world.map).filter(i => i.severity !== "INFO"), errors = validateWorld(world);
  const values = assessment.layouts.map(layout => layout.openingSpread);
  return <fieldset disabled={busy} className="studio-review">
    <div className="studio-panel-heading"><h2>Read the possibilities</h2><p>Geographic evidence for the game you want to play.</p></div>
    <div className="studio-review-status"><span className={`studio-dot ${errors.length ? "is-error" : ""}`} />{errors.length ? `${errors.length} placement issues` : "Placement checks pass"}</div>
    <section className="studio-analysis"><h3>Changing access</h3>{assessment.stages.map(stage => <div className="studio-stage-row" key={stage.id}><span>{stage.label}</span><strong>{stage.reachablePairs}/{stage.pairs}</strong><small>region pairs connected</small></div>)}<p>{assessment.layouts.length} plausible starting arrangements assessed. Civ V chooses actual starts.</p></section>
    <details open><summary>Strategic findings <span>{assessment.findings.length}</span></summary>{assessment.findings.length ? assessment.findings.map(finding => <div className="studio-finding" key={finding.id}><strong>{finding.label}</strong><p>{finding.detail}</p></div>) : <p className="studio-caption">No additional concerns in the screened geography. This does not predict human gameplay.</p>}</details>
    <details><summary>Settlement opportunities</summary><p className="studio-caption">Opening spread: {Math.min(...values).toFixed(0)}–{Math.max(...values).toFixed(0)}% across sampled arrangements.</p>{assessment.axes?.map(axis => <div className="studio-axis" key={axis.name}><strong>{axis.name}</strong><span>{axis.values.map(v => v < 0 ? "—" : v).join(" · ")}</span><small>{axis.unit}</small></div>)}{assessment.notes.map(note => <p key={note} className="studio-caption">{note}</p>)}</details>
    <details><summary>Improve opportunities</summary><Field label="Policy"><select value={balance} onChange={e => setBalance(e.target.value as typeof balance)}><option value="OPENING">Opening opportunities</option><option value="STRATEGIC">Broader opportunities</option><option value="SYMMETRIC">Rotational arena</option></select></Field><button className="studio-full" onClick={() => run({ kind: "REBALANCE", world, balance }, "Improved geographic opportunities")}>Preview improvement</button></details>
    <details><summary>Alternative foundations <span>{world.development.candidates.length}</span></summary>{world.development.candidates.map((candidate, i) => <div className="studio-finding" key={candidate.seed}><strong>Foundation {i + 1}{candidate.selected ? " · selected" : ""}</strong><p>{candidate.water.toFixed(0)}% water · {candidate.mountains.toFixed(0)}% mountains</p>{candidate.improvements.map((step, index) => <p key={index}>{step}</p>)}{!candidate.selected && candidate.recipe && <button onClick={() => run({ kind: "ALTERNATIVE", world, seed: candidate.seed }, `Alternative foundation ${i + 1}`)}>Preview foundation</button>}</div>)}</details>
    <details open={errors.length > 0}><summary>Inspect & repair <span>{issues.length}</span></summary>{issues.map(issue => <label className="studio-issue" key={issue.id}><input type="checkbox" disabled={!issue.mutation} checked={chosen.includes(issue.id)} onChange={e => setChosen(e.target.checked ? [...chosen, issue.id] : chosen.filter(id => id !== issue.id))} /><span><strong>{issue.title}</strong><small>{issue.detail}</small></span></label>)}{!issues.length && <p className="studio-caption">No repair findings.</p>}<div className="studio-two-buttons"><button onClick={() => setChosen(issues.filter(i => i.mutation && i.minimumProfile === "SAFE").map(i => i.id))}>Select safe fixes</button><button disabled={!chosen.length} onClick={() => run({ kind: "REPAIR", world, issues: chosen }, "Selected repairs")}>Preview fixes</button></div></details>
  </fieldset>;
}
