/* Real IndexedDB checks against a disposable database. */
document.getElementById('run').onclick=async()=>{
  const output=document.getElementById('results'),button=document.getElementById('run');button.disabled=true;output.textContent='Running';
  const name=`excogitare-history-check-${crypto.randomUUID()}`;let store=window.V3SnapshotStore.create(name),passed=[];
  const assert=(ok,message)=>{if(!ok)throw new Error(message);};
  const world=i=>({uid:i+1,title:`Snapshot ${i}`,kept:i===0,originalBytes:new Uint8Array([7,8,9]).buffer,map:{width:1,height:1,tiles:[{terrain:2,elevation:0,resource:255,resourceAmount:0,feature:255,wonder:255,river:0,continent:1}]}});
  try{
    for(let i=0;i<101;i++)await store.add(world(i));
    let saved=await store.load();assert(saved.history.length===100,'The cap is not 100.');assert(saved.history[0].title==='Snapshot 0'&&saved.history[0].kept,'The oldest bookmark was evicted.');assert(!saved.history.some(w=>w.title==='Snapshot 1'),'The oldest unbookmarked snapshot was not evicted.');assert(saved.history[1].title==='Snapshot 2','History order changed.');passed.push('100-snapshot cap evicts the oldest unbookmarked record');
    const lastId=saved.activeId;await store.close();store=window.V3SnapshotStore.create(name);saved=await store.load();assert(saved.history.length===100&&saved.activeId===lastId&&saved.history[0].kept,'Reload did not preserve history, bookmarks and selection.');assert(new Uint8Array(saved.history[0].originalBytes).join(',')==='7,8,9','Imported source bytes were lost.');passed.push('Reload preserves bookmarks, active selection and imported bytes');
    const selected=saved.history[2].historyId;await store.select(selected);assert((await store.load()).activeId===selected,'Selected snapshot was not remembered.');passed.push('Snapshot selection persists');
    await Promise.all(saved.history.map(w=>store.setKept(w.historyId,true)));const before=await store.load();let full=false;try{await store.add(world(102));}catch(error){full=error.code==='HISTORY_FULL';}saved=await store.load();assert(full,'All-bookmarked capacity did not return HISTORY_FULL.');assert(JSON.stringify(saved)===JSON.stringify(before),'Rejected insertion changed bookmarks, maps, order or selection.');passed.push('All-bookmarked capacity fails atomically without changing selection');
    let missing=false;try{await store.setKept('missing-snapshot',false);}catch{missing=true;}assert(missing&&JSON.stringify(await store.load())===JSON.stringify(before),'A missing-record update did not fail safely.');passed.push('Missing bookmark targets fail without modifying stored records');
    const released=saved.history[8].historyId;await store.setKept(released,false);await store.add(world(102));saved=await store.load();assert(saved.history.length===100&&!saved.history.some(w=>w.historyId===released),'Unbookmarking did not release the selected record for eviction.');assert(saved.history[0].kept&&saved.history.at(-1).historySequence===102,'Protected record or transaction sequence changed.');passed.push('Removing a bookmark makes only that record eligible for replacement');
    const releasedIds=saved.history.slice(1,4).map(w=>w.historyId);await Promise.all(releasedIds.map(id=>store.setKept(id,false)));await Promise.all([103,104,105].map(i=>store.add(world(i))));saved=await store.load();assert(saved.history.length===100&&new Set(saved.history.map(w=>w.historyId)).size===100,'Concurrent inserts violated capacity or identity.');assert(releasedIds.every(id=>!saved.history.some(w=>w.historyId===id))&&saved.history[0].kept,'Concurrent inserts removed a protected record.');passed.push('Concurrent insertion preserves bookmarks and the hard cap');
    output.textContent='PASSED\n'+passed.map(p=>'• '+p).join('\n');
  }catch(error){output.textContent='FAILED: '+error.message;}
  finally{await store.close();await new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase(name);request.onsuccess=resolve;request.onerror=()=>reject(request.error);});button.disabled=false;}
};
