import type { Civ5Map } from "./civ5-map.ts";
import { generateMap, type MapGenerationOptions } from "./map-generator.ts";
import { findLuaIncludes } from "./lua-project.ts";

function bytesToBase64(bytes: Uint8Array) {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  if (typeof btoa !== "function") throw new Error("Base64 encoding is not available in this environment.");
  return btoa(binary);
}

function base64ToText(value: string) {
  if (typeof atob === "function") {
    const binary = atob(value);
    return new TextDecoder().decode(Uint8Array.from(binary, (character) => character.charCodeAt(0)));
  }
  throw new Error("Base64 decoding is not available in this environment.");
}

function luaString(value: string) {
  return `"${value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n")}"`;
}

function luaArray(values: Array<string | number>) {
  return `{${values.map((value) => typeof value === "number" ? value : luaString(value)).join(",")}}`;
}

function xml(value: string) {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function slug(value: string) {
  return value.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "excogitare-map";
}

export type LuaCompatibilityReport = {
  compatible: boolean;
  title: string;
  details: string[];
  options?: MapGenerationOptions;
  execution: "NATIVE" | "SANDBOX" | "UNKNOWN";
};

export function inspectLuaMapScript(source: string): LuaCompatibilityReport {
  const marker = source.match(/^-- EXCOGITARE_CONFIG_BASE64:([A-Za-z0-9+/=]+)$/m);
  if (marker) {
    try {
      const options = JSON.parse(base64ToText(marker[1])) as MapGenerationOptions;
      return {
        compatible: true,
        title: "Excogitare map script",
        details: ["Embedded generation settings found", "Safe native regeneration available", "No external Civ V database calls required"],
        options,
        execution: "NATIVE",
      };
    } catch {
      return { compatible: false, title: "Damaged Excogitare script", details: ["The embedded generation settings could not be decoded"], execution: "UNKNOWN" };
    }
  }
  const details: string[] = [];
  const includes = findLuaIncludes(source);
  if (/function\s+GetMapScriptInfo\s*\(/.test(source)) details.push("Map-script metadata entry point found");
  if (/function\s+GetMapInitData\s*\(/.test(source)) details.push("Script-controlled dimensions and wrapping found");
  if (/function\s+GeneratePlotTypes\s*\(/.test(source)) details.push("Plot generation entry point found");
  if (/\bCustomOptions\s*=|\bGetCustomOptions\s*\(/.test(source)) details.push("Script-defined map options found");
  if (/\bMap\./.test(source)) details.push("Uses the Civ V Map API");
  if (/\bGameInfo\./.test(source)) details.push("Uses the Civ V game database");
  if (/\bDB\./.test(source)) details.push("Direct database queries will use the limited compatibility database");
  if (includes.length) details.push(`${includes.length} named Lua include${includes.length === 1 ? "" : "s"} requested`);
  const recognized = /function\s+(?:GetMapScriptInfo|GenerateMap|GeneratePlotTypes)\s*\(/.test(source);
  return {
    compatible: false,
    title: recognized ? "Civ V map project detected" : "Not recognized as a Civ V map script",
    details: details.length ? details : ["No supported map-generation entry points were found"],
    execution: recognized ? "SANDBOX" : "UNKNOWN",
  };
}

export function mapFromLuaScript(source: string) {
  const report = inspectLuaMapScript(source);
  if (!report.compatible || !report.options) throw new Error("This script needs Civ V API compatibility that is not available in the native preview yet.");
  return { map: { ...generateMap(report.options), source: "script" as const }, report };
}

export function createLuaMapScript(map: Civ5Map) {
  const config = map.generation
    ? bytesToBase64(new TextEncoder().encode(JSON.stringify(map.generation)))
    : "";
  const terrainNames = luaArray(map.terrains);
  const featureNames = luaArray(map.features);
  const resourceNames = luaArray(map.resources);
  const terrain = luaArray(map.tiles.map((tile) => tile.terrain + 1));
  const features = luaArray(map.tiles.map((tile) => tile.feature === 255 ? 0 : tile.feature + 1));
  const resources = luaArray(map.tiles.map((tile) => tile.resource === 255 ? 0 : tile.resource + 1));
  const elevation = luaArray(map.tiles.map((tile) => tile.elevation));
  const rivers = luaArray(map.tiles.map((tile) => tile.river));
  return `-- Generated by Excogitare
${config ? `-- EXCOGITARE_CONFIG_BASE64:${config}` : ""}
local WIDTH, HEIGHT, WRAP_X = ${map.width}, ${map.height}, ${map.wraps ? "true" : "false"}
local terrainNames = ${terrainNames}
local featureNames = ${featureNames}
local resourceNames = ${resourceNames}
local terrainData = ${terrain}
local featureData = ${features}
local resourceData = ${resources}
local elevationData = ${elevation}
local riverData = ${rivers}

function GetMapScriptInfo()
  return {
    Name = ${luaString(map.name)},
    Description = ${luaString(map.description)},
    IsAdvancedMap = 0,
    SupportsMultiplayer = true,
    CustomOptions = {}
  }
end

function GetMapInitData(worldSize)
  return { Width = WIDTH, Height = HEIGHT, WrapX = WRAP_X }
end

local function eachPlot(callback)
  for y = 0, HEIGHT - 1 do
    for x = 0, WIDTH - 1 do
      local index = y * WIDTH + x + 1
      callback(Map.GetPlot(x, y), index)
    end
  end
end

function GeneratePlotTypes()
  eachPlot(function(plot, index)
    local terrainName = terrainNames[terrainData[index]]
    if terrainName == "TERRAIN_OCEAN" or terrainName == "TERRAIN_COAST" then
      plot:SetPlotType(PlotTypes.PLOT_OCEAN)
    elseif elevationData[index] == 2 then
      plot:SetPlotType(PlotTypes.PLOT_MOUNTAIN)
    elseif elevationData[index] == 1 then
      plot:SetPlotType(PlotTypes.PLOT_HILLS)
    else
      plot:SetPlotType(PlotTypes.PLOT_LAND)
    end
  end)
end

function GenerateTerrain()
  eachPlot(function(plot, index)
    local row = GameInfo.Terrains[terrainNames[terrainData[index]]]
    if row then plot:SetTerrainType(row.ID, false, false) end
  end)
end

function AddFeatures()
  eachPlot(function(plot, index)
    local featureIndex = featureData[index]
    if featureIndex > 0 then
      local row = GameInfo.Features[featureNames[featureIndex]]
      if row then plot:SetFeatureType(row.ID) end
    end
    local resourceIndex = resourceData[index]
    if resourceIndex > 0 then
      local resource = GameInfo.Resources[resourceNames[resourceIndex]]
      if resource then plot:SetResourceType(resource.ID, 1) end
    end
  end)
end

function AddRivers()
  eachPlot(function(plot, index)
    local river = riverData[index]
    if bit.band(river, 1) ~= 0 then plot:SetWOfRiver(true, FlowDirectionTypes.FLOWDIRECTION_SOUTH) end
    if bit.band(river, 2) ~= 0 then plot:SetNWOfRiver(true, FlowDirectionTypes.FLOWDIRECTION_NORTHEAST) end
    if bit.band(river, 4) ~= 0 then plot:SetNEOfRiver(true, FlowDirectionTypes.FLOWDIRECTION_SOUTHEAST) end
  end)
end
`;
}

export function createModInfo(map: Civ5Map, luaFileName: string) {
  const identifier = `excogitare-${slug(map.name)}`;
  return `<?xml version="1.0" encoding="utf-8"?>
<Mod id="${identifier}" version="1">
  <Properties>
    <Name>${xml(map.name)}</Name>
    <Description>${xml(map.description)}</Description>
    <Authors>Excogitare</Authors>
    <SupportsSinglePlayer>1</SupportsSinglePlayer>
    <SupportsMultiplayer>1</SupportsMultiplayer>
    <SupportsHotSeat>1</SupportsHotSeat>
    <SupportsMac>1</SupportsMac>
    <AffectsSavedGames>0</AffectsSavedGames>
  </Properties>
  <Files>
    <File import="0">${xml(luaFileName)}</File>
  </Files>
  <EntryPoints>
    <EntryPoint type="MapScript" file="${xml(luaFileName)}">
      <Name>${xml(map.name)}</Name>
      <Description>${xml(map.description)}</Description>
    </EntryPoint>
  </EntryPoints>
</Mod>
`;
}

export function mapExportBaseName(map: Civ5Map) {
  return slug(map.name);
}
