/* Session-only history study. Project import/export are interface previews. */
(() => {
  const original=current;original.change='Original';original.kept=true;
  const all=original.map.tiles.map((_,i)=>i),versions=[['woodland','More woodland'],['pass','Lower mountains'],['redistribute','New resources']];
  history=[original,...versions.map(([action,label])=>({...original,uid:++serial,kept:action==='redistribute',change:label,map:window.V3ExistingRules.refineLocal(original.map,action,all,'moderate').map}))];
  let filter='all',comparison=null,compareView='changes';
  const panel=document.createElement('aside');panel.className='history-workspace paper';panel.setAttribute('aria-label','History and projects');panel.innerHTML='<header><h3>History</h3><button class="text-button" id="close-history-study">Close</button></header><div class="history-filter"><button data-history-filter="all" aria-pressed="true">All versions</button><button data-history-filter="bookmarked" aria-pressed="false">Bookmarked</button></div><input class="history-search" type="search" aria-label="Find a version" placeholder="Find a version"><div class="history-versions"></div><section class="comparison-controls" hidden><p>Compare versions</p><div class="history-filter"><button data-comparison-view="original">Original</button><button data-comparison-view="version">Version</button><button data-comparison-view="changes">Changes</button></div><small class="comparison-summary"></small><div class="comparison-end"><button class="text-button" id="end-history-compare">Close comparison</button><button class="outline" id="use-history-version">Use version</button></div></section><div class="project-actions"><button class="text-button" id="open-project-study">Open project</button><button class="text-button" id="save-project-study">Save project</button></div>';
  const workspace=document.querySelector('.workspace');workspace.append(panel);const opener=document.createElement('button');opener.className='history-reopen paper';opener.textContent='History';opener.setAttribute('aria-expanded','true');opener.onclick=()=>{panel.hidden=!panel.hidden;opener.setAttribute('aria-expanded',String(!panel.hidden));};workspace.append(opener);
  const note=document.createElement('small');note.className='iteration-note';note.textContent='Design mockup · session history · project transfer preview';workspace.append(note);
  const list=panel.querySelector('.history-versions'),search=panel.querySelector('.history-search'),controls=panel.querySelector('.comparison-controls');
  const baseSetCurrent=setCurrent;setCurrent=function(world,options){baseSetCurrent(world,options);renderVersions();};
  const baseDraw=drawTiles;drawTiles=function(context,map,layers,marked){baseDraw(context,map,layers,comparison&&compareView!=='changes'?[]:marked);};
  function closeComparison(){if(comparison){endPreview();comparison=null;}controls.hidden=true;renderVersions();}
  function compare(world){if(guardPreview())return;if(world===current)return;if(world.map.width!==current.map.width||world.map.height!==current.map.height){toast('This mockup compares versions with matching map dimensions.');return;}comparison={original:current,version:world};compareView='changes';startPreview(world.map,'Compare versions','','comparison');if(!preview){comparison=null;return;}controls.hidden=false;panel.querySelector('.comparison-summary').textContent=`${current.change} → ${world.change} · ${preview.changed.length} tiles differ`;syncComparison();renderVersions();}
  function syncComparison(){for(const button of panel.querySelectorAll('[data-comparison-view]'))button.setAttribute('aria-pressed',String(button.dataset.comparisonView===compareView));showOriginal=compareView==='original';renderMap();}
  function renderVersions(){
    const query=search.value.toLowerCase(),worlds=[...history].reverse().filter(world=>(filter!=='bookmarked'||world.kept)&&`${world.title} ${world.change}`.toLowerCase().includes(query));list.replaceChildren();
    for(const world of worlds){const row=document.createElement('div');row.className='version-row';const pick=document.createElement('button');pick.className='version-pick';pick.setAttribute('aria-label',`View ${world.change}`);pick.setAttribute('aria-pressed',String(world===current));const thumb=document.createElement('canvas');thumb.width=192;thumb.height=112;thumb.setAttribute('aria-hidden','true');paintThumbnail(thumb,world);const copy=document.createElement('span'),title=document.createElement('strong'),subtitle=document.createElement('small');title.textContent=world.change;subtitle.textContent=world.kept?'Bookmarked':world.title;copy.append(title,subtitle);pick.append(thumb,copy);pick.disabled=!!comparison;pick.onclick=()=>{if(!guardPreview())setCurrent(world);};const compareButton=document.createElement('button');compareButton.className='text-button';compareButton.textContent='Compare';compareButton.setAttribute('aria-label',`Compare ${world.change}`);compareButton.disabled=world===current||!!comparison;compareButton.onclick=()=>compare(world);row.append(pick,compareButton);list.append(row);}
    if(!worlds.length){const empty=document.createElement('p');empty.textContent='No matching versions.';empty.style='font-size:11px;color:var(--muted)';list.append(empty);}
  }
  for(const button of panel.querySelectorAll('[data-history-filter]'))button.onclick=()=>{filter=button.dataset.historyFilter;for(const other of panel.querySelectorAll('[data-history-filter]'))other.setAttribute('aria-pressed',String(other===button));renderVersions();};search.oninput=renderVersions;
  for(const button of panel.querySelectorAll('[data-comparison-view]'))button.onclick=()=>{compareView=button.dataset.comparisonView;syncComparison();};
  panel.querySelector('#end-history-compare').onclick=closeComparison;panel.querySelector('#use-history-version').onclick=()=>{const world=comparison?.version;closeComparison();if(world)setCurrent(world);};panel.querySelector('#close-history-study').onclick=()=>{closeComparison();panel.hidden=true;opener.setAttribute('aria-expanded','false');opener.focus();};
  new MutationObserver(()=>renderVersions()).observe($('world-list'),{attributes:true,subtree:true,attributeFilter:['aria-description']});
  const dialog=document.createElement('dialog');dialog.className='project-dialog';document.body.append(dialog);
  function project(mode){
    const saving=mode==='save';dialog.replaceChildren();const heading=document.createElement('h3');heading.textContent=saving?'Save project':'Open project';dialog.append(heading);
    if(saving){const label=document.createElement('label');label.textContent='Project name';const name=document.createElement('input');name.value=current.title;label.append(name);const include=document.createElement('label');include.textContent='Include';const select=document.createElement('select');select.setAttribute('aria-label','Project contents');for(const title of ['Current map + bookmarked versions','Current map only','All versions']){const option=document.createElement('option');option.textContent=title;select.append(option);}include.append(select);dialog.append(label,include);}else{const drop=document.createElement('div');drop.className='project-drop';drop.textContent='Drop an .excogitare project here';dialog.append(drop);}
    const description=document.createElement('p');description.textContent=saving?'Keep maps, generation settings and bookmarks together.':'Resume a saved project with its maps, settings and bookmarks.';const limitation=document.createElement('p');limitation.textContent='Design preview: no project file is read or written.';const footer=document.createElement('footer'),cancel=document.createElement('button'),proceed=document.createElement('button');cancel.className='text-button';cancel.textContent='Cancel';cancel.onclick=()=>dialog.close();proceed.className='primary';proceed.textContent=saving?'Save project':'Choose project';proceed.onclick=()=>{dialog.close();toast('Project transfer is a design preview.');};footer.append(cancel,proceed);dialog.append(description,limitation,footer);dialog.showModal();
  }
  panel.querySelector('#open-project-study').onclick=()=>project('open');panel.querySelector('#save-project-study').onclick=()=>project('save');
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!dialog.open&&comparison)closeComparison();});
  setCurrent(original);renderVersions();
})();
