/* Illustrative selective regeneration; the production generator is not changed. */
(() => {
  setMode('refine');
  const body=document.querySelector('.rf-local-body'),editor=body.querySelector('.rf-section:not(.rf-area)'),ready=document.querySelector('.rf-ready'),originalButton=ready.querySelector('button'),originalNote=ready.querySelector('small');
  editor.hidden=true;
  const options=document.createElement('section');options.className='regeneration-options';body.append(options);
  function field(label,values,id){const row=document.createElement('label');row.className='rf-field';const caption=document.createElement('span');caption.textContent=label;const input=document.createElement('select');input.id=id;input.dataset.refineMenu='';input.setAttribute('aria-label',label);for(const [value,text] of values){const option=document.createElement('option');option.value=value;option.textContent=text;input.append(option);}row.append(caption,input);options.append(row);return input;}
  const reroll=field('Reroll',[['resources','Resources'],['vegetation','Vegetation'],['relief','Relief']],'study-reroll');
  const variation=field('Variation',[['light','Light'],['moderate','Moderate'],['strong','Strong']],'study-variation');variation.value='moderate';
  const heading=document.createElement('h3');heading.textContent='Keep';const kept=document.createElement('div');kept.className='keep-options';options.append(heading,kept);
  const locks=new Map();for(const [key,name] of [['coastline','Coastline'],['relief','Relief'],['climate','Climate'],['vegetation','Vegetation'],['starts','Starts'],['resources','Resources']]){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=key!=='resources';input.setAttribute('aria-label',`Keep ${name.toLowerCase()}`);label.append(input,document.createTextNode(name));kept.append(label);locks.set(key,input);}
  const scopeNote=document.createElement('p');scopeNote.className='regeneration-scope';scopeNote.textContent='Changes stay inside the selection.';options.append(scopeNote);const clear=editor.querySelector('.rf-local-clear');if(clear)options.append(clear);
  const note=document.createElement('small'),button=document.createElement('button');button.className='primary';button.textContent='Preview regeneration';ready.replaceChildren(note,button);
  const status=document.createElement('small');status.className='iteration-note';status.textContent='Design mockup · illustrative regeneration · session only';document.querySelector('.workspace').append(status);
  function sync(){const global=document.querySelector('.rf-global').open,locked=locks.get(reroll.value)?.checked,text=global?originalNote.textContent:locked?`Uncheck ${reroll.selectedOptions[0].textContent} to reroll it`:selection.length?`${selection.length} tiles · ${[...locks.values()].filter(input=>input.checked).length} elements kept`:'Select a region, area or tile';if(note.textContent!==text)note.textContent=text;const label=global?'Preview global changes':'Preview regeneration';if(button.textContent!==label)button.textContent=label;const disabled=global?originalButton.disabled:!!preview||historyBusy||generationPending||!!locked||!selection.length;if(button.disabled!==disabled)button.disabled=disabled;for(const input of [reroll,variation,...locks.values()])if(input.disabled!==!!preview)input.disabled=!!preview;}
  button.onclick=()=>{if(document.querySelector('.rf-global').open){originalButton.onclick();return;}if(guardPreview())return;try{const action={resources:'redistribute',vegetation:'thin',relief:'pass'}[reroll.value],result=window.V3ExistingRules.refineLocal(current.map,action,selection,variation.value);startPreview(result.map,`Regenerate ${reroll.value}`,`Illustrative · ${result.movedResources||result.changed.length} ${result.movedResources?'deposits moved':'tiles changed'}`,'study');}catch(error){toast(error.message);}sync();};
  options.addEventListener('change',sync);new MutationObserver(sync).observe(document.querySelector('#refine-panel'),{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','disabled','open']});new MutationObserver(sync).observe(document.querySelector('.refine-footer'),{attributes:true,subtree:true,attributeFilter:['hidden']});
  requestAnimationFrame(()=>{const region=document.querySelector('select[aria-label="Region type"]');region.value='landmass';region.dispatchEvent(new Event('change',{bubbles:true}));const visited=new Set();let largest=[];for(let i=0;i<current.map.tiles.length;i++){if(visited.has(i)||window.V3ExistingRules.isWaterTerrain(current.map,current.map.tiles[i]))continue;const area=window.V3ExistingRules.refineGeometry.connected(current.map,i,'landmass');for(const index of area)visited.add(index);if(area.length>largest.length)largest=area;}selection=largest;updateSelection();sync();});
})();
